# Lab 2: Q-Learning

In [218]:
import gym
import numpy as np
import random
#import matplotlib.pyplot as plt
#%matplotlib inline

### Load the environment

In [219]:
env = gym.make('FrozenLake-v0')

[2017-09-26 10:05:49,450] Making new env: FrozenLake-v0


### Implement Q learning algorithm

In [220]:
#Initialize table with all zeros in Q(s, a) table
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [221]:
# Set learning parameters

# Learning rate
lr = .8

# Discount factor
gamma = .95

# Time horizon
num_episodes = 5000

# epsilon
epsilon = .9

In [222]:
rewards = []
for i in range(num_episodes):
 
    s = env.reset()
    episode_reward = 0
    done = False
    timestep = 0
    
    if(num_episodes % 100 == 0):
        epsilon *= .99
#         print(epsilon)
    
    for timestep in range(100):
        #TODO: Choose an action by greedily (with noise) picking from Q table
        random_a = random.randint(0,3)
        a = Q[s].argmax(axis=0) if (random.uniform(0, 1) > epsilon) else random_a
        
#         if(i < 100 or i > 4000):
#             print(i, a, Q[s].argmax(axis=0), random_a)
        
        #Get new state and reward from environment
        next_s, reward, done, info = env.step(a)

        #TODO: Update Q-Table with new knowledge
        max_a = Q[next_s].argmax(axis=0)
        if done is not True:
            Q[s][a] = Q[s][a] + lr * (reward + gamma * Q[next_s][max_a] - Q[s][a])
        else:
            Q[s][a] = Q[s][a] + lr * (reward - Q[s][a])
        
        episode_reward += reward
        s = next_s
        
        if done == True:
            break

    rewards.append(episode_reward)

In [223]:
print("Score over time: " +  str(sum(rewards)/num_episodes))

Score over time: 0.6518


In [224]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  3.23927146e-01   6.88846634e-04   2.69654525e-03   2.29677811e-03]
 [  1.15211619e-04   2.98826049e-07   2.56872406e-05   1.81673284e-01]
 [  6.38437028e-04   0.00000000e+00   1.72149331e-03   1.05171969e-01]
 [  2.26928443e-04   0.00000000e+00   3.50962992e-04   6.39113337e-02]
 [  3.86882497e-01   1.31916055e-03   2.73675116e-03   1.57448447e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.81212138e-06   3.23661218e-06   2.48550874e-01   4.97170839e-06]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.13977527e-03   1.92267229e-03   3.17972458e-03   5.40211067e-01]
 [  3.28949540e-03   6.45423657e-01   2.09102785e-03   1.48369435e-03]
 [  7.82476315e-01   0.00000000e+00   0.00000000e+00   1.55723250e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.73980559e-03   1.38769357e-02   8.74949423e-01   7